/*
Even Fibonacci numbers

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class EulerProblem2 {
    public static void main(String[] args){
        long[] Tmp = new long[3];
        long sum = 2;
        Tmp[0] = 1;
        Tmp[1] = 2;
        Tmp[2] = 3;

        while(Tmp[2] <= 4000000){
            if (Tmp[2]%2 == 0) sum += Tmp[2];
            Tmp[0] = Tmp[1];
            Tmp[1] = Tmp[2];
            Tmp[2] = Tmp[1] + Tmp[0];
         }
        System.out.println(sum);
    }
}
